etcd:
  image: rancher/etcd:v2.3.7-9
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_soft: etcd=true
    io.rancher.scheduler.affinity:host_label_soft_ne: cassandra=true
  environment:
    RANCHER_DEBUG: 'true'
    BACKUP_PERIOD: 15m
    BACKUP_RETENTION: 24h
    EMBEDDED_BACKUPS: 'false'
cassandra:
  image: llparse/cassandra:v3.7
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_soft: cassandra=true
    io.rancher.scheduler.affinity:host_label_soft_ne: etcd=true
  environment:
    RANCHER_DEBUG: 'true'
    CASSANDRA_CLUSTER_NAME: streamingchan
    HEAP_NEWSIZE: ${HEAP_NEWSIZE}
    MAX_HEAP_SIZE: ${MAX_HEAP_SIZE}
node:
  image: llparse/streamingchan:v1.0
  command: >
    -node
    -cassandra cassandra
    -clustername streamingchan
    -etcd http://etcd:2379
    -httpport 3333
    -keyspace chan
    -tw ${THREAD_WORKERS}
    ${NODE_ARGS}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_soft_ne: cassandra=true,etcd=true
  links:
  - etcd
  - cassandra
api:
  image: llparse/streamingchan:v1.0
  command: >
    -api
    -cassandra cassandra
    -clustername streamingchan
    -etcd http://etcd:2379
    -httpport 4000
    -keyspace chan
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_soft_ne: cassandra=true,etcd=true
  ports:
  - 4000:4000/tcp
  links:
  - etcd
  - cassandra